package org.example.sharedprompts.domain.prompt.common.enums.action;

import org.example.sharedprompts.domain.prompt.common.enums.action.metadata.ActionTypeMetadataLoader;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Round-trip: writes current loader content back to action-type-*.properties.
 * Metadata lives in properties only; run manually to persist in-memory edits or after adding new keys.
 * Disabled by default.
 */
@Disabled("Run manually to rewrite action-type-*.properties from loader when needed")
class ActionTypeMetadataGeneratorTest {

    @Test
    void roundTripMetadataPropertiesFiles() throws Exception {
        Map<String, String> keyToBehavior = new TreeMap<>();
        ActionTypeMetadataLoader.loadKeyToOutputBehavior().forEach((k, v) -> keyToBehavior.put(k, v.name()));

        Map<String, String> keyToDomain = new TreeMap<>();
        ActionTypeMetadataLoader.loadKeyToDomain().forEach((k, v) -> keyToDomain.put(k, v.name()));

        assertThat(keyToBehavior).isNotEmpty();
        assertThat(keyToDomain).isNotEmpty();

        Path resourcesDir = Paths.get("src/main/resources");
        if (!Files.isDirectory(resourcesDir)) {
            resourcesDir = Paths.get("sharedPrompts/src/main/resources");
        }
        if (!Files.isDirectory(resourcesDir)) {
            throw new IllegalStateException("Could not find src/main/resources; run from module root");
        }

        List<String> behaviorLines = new ArrayList<>();
        behaviorLines.add("# Generated by ActionTypeMetadataGeneratorTest. Do not edit by hand.");
        keyToBehavior.forEach((k, v) -> behaviorLines.add(k + "=" + v));

        List<String> domainLines = new ArrayList<>();
        domainLines.add("# Generated by ActionTypeMetadataGeneratorTest. Do not edit by hand.");
        keyToDomain.forEach((k, v) -> domainLines.add(k + "=" + v));

        Path behaviorFile = resourcesDir.resolve(ActionTypeMetadataLoader.OUTPUT_BEHAVIOR_RESOURCE);
        Path domainFile = resourcesDir.resolve(ActionTypeMetadataLoader.DOMAIN_RESOURCE);

        Files.write(behaviorFile, behaviorLines);
        Files.write(domainFile, domainLines);
    }
}
